language: php

php:
  - 7.1

sudo: false

install:
  - travis_retry composer update --no-interaction --no-progress

script:
  - vendor/bin/codecept run unit
  - find src/ -type f -print0 | xargs -0 -n1 php -l
  - vendor/bin/phpcs src/ --standard=psr2

notifications:
  email:
    - sid@sidroberts.co.uk
